### ISSUE TITLE
Error with missing file "gBinder*.pdb.seq"

### ISSUE THREAD

**Issue by pbunk2555** [XingchengLin/RACER#1]
I enjoyed reading your paper on the RACER model and was looking at implementing it myself to run on another data set.

While trying the demo from GitHub, I ran into an error which seems to relate to missing files. The for_gBinder_sequences_4mac.sh script is looking for a file called gBinder*.pdb.seq which doesn’t seem to exist in the repository. Is this something that should be created in the demo or are these files that we would have to provide? If so, what is the format of these files?

For reference, I am running the program on a MacBookPro with an Apple M1 chip and macOS Monterey (Version 12.0.1), with the RACER software installed from the master branch on 04/17/22. The Modeller version I am using is 10.2.

Thank you very much for your help.

**Comment by XingchengLin** [comment]
This warning message came from a redundant part of the codes. This part should not affect any prediction result, and I have removed it. Thanks for catching it
